### ISSUE TITLE
Некоторые фамилии определяет неверно

### ISSUE THREAD

**Issue by EugeneRymarev** [datacoon/russiannames#3]
Приветствую!
Фамилию "Афанасьева" определяет, как отчество.
Могу сюда добавлять и другие, которые ошибочно определяет по мере нахождения.

**Comment by EugeneRymarev** [comment]
- **Антанович** тоже в отчество определило, но тут хотя бы есть на то причины - это похоже на мужское отчество. На деле это несклоняемая фамилия.
- **Емельянова** опять отчество, хотя отчество "Емельяновна" было бы.
- **Степанова**
- **Михайлович** - думаю аналогично первому варианту определилось в отчество

**Comment by ivbeg** [comment]
Да, это ошибка в базе, некоторое количество фамилий случайно оказались в таблице отчеств. Я запущу валидацию. 
Пока быстрый патч для MongoDB - удалить эти фамилии из таблицы midnames
use names
db.midnames.remove({'text' : 'Афанасьева'})
db.midnames.remove({'text' : 'Емельянова'})
db.midnames.remove({'text' : 'Степанова'})

С фамилиями на "ич" сложнее, тут всегда могут быть неоднозначности

**Comment by EugeneRymarev** [comment]
- **Андреева**
- **Гаврилова**

**Comment by EugeneRymarev** [comment]
Сейчас обрабатываю базу клиентов и иногда встречается такое, что отчество стоит перед именем и **russiannames** определяет его сразу в фамилии, хотя это точно отчество - **Григорьевна Мария**

**Comment by EugeneRymarev** [comment]
- **Константинова**

**Comment by ivbeg** [comment]
Закрыто как давно не обновлявшееся
