### ISSUE TITLE
Источник данных

### ISSUE THREAD

**Issue by Nokvel** [datacoon/russiannames#4]
Доброго времени суток!
Какой источник данных у имен и фамилий, а так же какой период обновления?
Спасибо.

**Comment by ivbeg** [comment]
Добрый день @Nokvel

Данные собирались из разного рода общедоступных, в основном государственных, открытых данных. Цели обновлять имена и фамилии не было, целевой результат - алгоритм, а не базы ФИО. Там базы скорее надо чистить чем расширять

Иван
