### ISSUE TITLE
Ссылки на документацию и БД не работают

### ISSUE THREAD

**Issue by EvgeneKuklin** [datacoon/russiannames#5]
https://russiannames.readthedocs.io/en/latest/
https://github.com/datacoon/russiannames/blob/master/data/bson/db_dump_bson.zip

**Comment by ivbeg** [comment]
База вот тут https://github.com/datacoon/russiannames/blob/master/data/bson/russiannames_db_bson.zip , а с документацией разбираюсь

**Comment by epogrebnyak** [comment]
Может забилдить документацию на Github Pages? Readthedocs что-то не показывает

**Comment by ivbeg** [comment]
@epogrebnyak я попробую перезапустить сборщик документации, честно говоря совсем просто забыл про эту багу

**Comment by ivbeg** [comment]
Исправил - https://russiannames.readthedocs.io/en/latest/index.html#
Форматирование не до конца работает потому что README в формате .md, а не .rst, но хотя бы стало пригодно для работы
