### ISSUE TITLE
Альтернативные БД

### ISSUE THREAD

**Issue by vkudyushev** [datacoon/russiannames#6]
Приветствую! отличный пакет, спасибо, что выложили в open source!
не думали ли вы о реализации поддержки других БД? например, in-memory SQLite. 
Возможно этот вариант будет работать быстрее, чем Mongo.
что думаете?

**Comment by vkudyushev** [comment]
к слову, на руках достаточное количество различных резюме и т.п., можно попробовать обновить словари

**Comment by ivbeg** [comment]
Добрый день! Идея хорошая, но пока не доходили руки и никто не жаловался на производительность. По мне так In-memory базы тут хуже потому что объём данных большой и базу данных нельзя будет отделить от обработчика данных.

База резюме - это очень хорошо, если можете поделиться то можно интегрировать в общий массив.

**Comment by vkudyushev** [comment]
могу вывести csv со следующими полями: фамилия, имя, отчество, пол. количественную оценку сложно пока дать - процесс импорта ещё идёт.

**Comment by ivbeg** [comment]
Отлично. Этого всего вполне достаточно.

**Comment by wb-08** [comment]
> Приветствую! отличный пакет, спасибо, что выложили в open source!
> не думали ли вы о реализации поддержки других БД? например, in-memory SQLite.
> Возможно этот вариант будет работать быстрее, чем Mongo.
> что думаете?

Добрый день, я сделал альтернативу: https://github.com/wb-08/SlavicNames

**Comment by ivbeg** [comment]
> 
> 

> Добрый день, я сделал альтернативу: https://github.com/wb-08/SlavicNames

Отлично! Добавлю ссылку на Ваш проект в описание
