### ISSUE TITLE
What is the source of the datasets?

### ISSUE THREAD

**Issue by davidam** [datacoon/russiannames#7]
Congratulations by the effort in this project.

I would like to know the source of the datasets used in this project. I would like include it in Damegender (https://github.com/davidam/damegender) and I used explain how I have retrieved the data and I am giving statistical institutions as source, for instance, sites as https://www.ssa.gov/oact/babynames/limits.html

Thanks in advance.

**Comment by ivbeg** [comment]
This dataset compiled from assorted public databases like phone databases, persons contacts in public procurement databases and so on. I can't reconstuct all sources right now, it was too many years ago.
So this dataset is far from ideal, it's not ideally clean, but so big as it was possible to create.

Another lesser and compatible dataset https://ngodata.ru/dataset/russiannames created from Russian registry of companies. It has lesser number of names, midnames and surnames, but much more clean. It was created from government database httpp://egrul.nalog.ru
